spring.application.name=portfolio
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=${DB_DIALECT}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}
spring.jpa.show-sql=${DB_SHOW_SQL}

server.port=${SERVER_PORT}
spring.security.user.name=${ADMIN_USERNAME}
spring.security.user.password=${ADMIN_PASSWORD}


spring.ai.mistralai.api-key=${MISTRAL_API_KEY}

# Email Configuration
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${EMAIL_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${EMAIL_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${EMAIL_STARTTLS_REQUIRED}